### ISSUE TITLE
startOnyxButton in OnyxSetupActivity is disabled by default

### ISSUE THREAD

**Issue by eolszewski** [DFTinc/onyx-5.0-demo#2]
https://github.com/DFTinc/onyx-5.0-demo/blob/master/app/src/main/java/com/dft/onyx50helloworld/OnyxSetupActivity.java#L132

^ Why is this set in this manner?

**Comment by Jaroslav84** [comment]
The button becomes enabled as soon as Onyx Configuration has completed. See callback:

```
onyxCallback = new OnyxConfiguration.OnyxCallback() {
            @Override
            public void onConfigured(Onyx configuredOnyx) {
                application.setConfiguredOnyx(configuredOnyx);
                startOnyxButton.setEnabled(true);
            }
        };
```

**Comment by RussianRoulette84** [comment]
LINE 42 in OnyxSetupActivity.java -> onCreate(): 
```
setupOnyx(this.activity);
```  
was removed. Put it back :) because the button gets enabled after Onyx Configuration process finishes (callback).
