### ISSUE TITLE
Crash on 'startOnyx'

### ISSUE THREAD

**Issue by eolszewski** [DFTinc/onyx-5.0-demo#3]
`
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.dft.onyxcamera.config.Onyx.create(android.app.Activity)' on a null object reference at com.dft.onyx50helloworld.OnyxActivity.onResume(OnyxActivity.java:23)
`

I'm running this in a simulator - is this a problem?

**Comment by eolszewski** [comment]
Yeah, seems like `configuredOnyx` is not being instantiated.

There's also the error `failed to make and chown /acct/uid_10053: Read-only file system`

Not sure what is being created there, but that is the only other error.

**Comment by eolszewski** [comment]
Likely a problem with the simulator's SD, I'll post back with a solution.

**Comment by eolszewski** [comment]
Tried this on on a hard device and still running into the same crash (sans the read-only file system).

**Comment by mjwheatley** [comment]
I believe this was caused by changing
`startOnyxButton.setEnabled(false);` from `false` to `true` therefore allowing a call to try and launch Onyx before it has been configured.
